apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: ms-world
  name: ms-world
  namespace: pact
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-world
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ms-world
      name: ms-world
    spec:
      containers:
      - image: localhost:32057/ms-world
        imagePullPolicy: Always
        name: ms-world
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-world
  name: ms-world
  namespace: pact
spec:
  ports:
  - name: tcp-9001-9001-dl3tp
    nodePort: 32012
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: ms-world
  sessionAffinity: None
  type: LoadBalancer
